#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#

# # global settings
yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_shadow off \
	window_animation_duration 0.1 \
	window_opacity_duration 0.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 1.0 \
	insert_feedback_color 0x00d75f5f \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 16 \
	bottom_padding 16 \
	left_padding 16 \
	right_padding 16 \
	window_gap 06 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap \
	external_bar all:35:0
#
yabai -m rule --add app="^System Settings$" sticky=on manage=off
# yabai -m rule --add app="^zoom.us$" sticky=on manage=off
yabai -m rule --add app="Stats" sticky=on manage=off
yabai -m rule --add app="Calculator" sticky=on manage=off
yabai -m rule --add app="^Finder$" sticky=on manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on manage=off
yabai -m rule --add app="^System Information$" sticky=on manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on manage=off
yabai -m rule --add app="Slack" space=1
yabai -m rule --add app="kitty" space=2
yabai -m rule --add app="^Google Chrome$" space=3

# yabai -m config window_border on | off
# yabai -m config window_border_width 6
# yabai -m config active_window_border_color 0xff775759
# yabai -m config normal_window_border_color 0xff555555

echo "yabai configuration loaded.."
